"""add story narrative and common_setting

Revision ID: 021cba9c6779
Revises: 2c9c27b5ec53
Create Date: 2026-04-04 20:34:25.714131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021cba9c6779'
down_revision = '2c9c27b5ec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narrative', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('common_setting', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('common_setting')
        batch_op.drop_column('narrative')

    # ### end Alembic commands ###
