"""add stories prompt_basis

Revision ID: 2c9c27b5ec53
Revises: fe2630633783
Create Date: 2026-04-04 19:59:09.836888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9c27b5ec53'
down_revision = 'fe2630633783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_basis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('prompt_basis')

    # ### end Alembic commands ###
