"""initial schema

Revision ID: fe2630633783
Revises: 
Create Date: 2026-04-04 17:40:00.450068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2630633783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('sd_model', sa.String(length=200), nullable=True),
    sa.Column('lora_name', sa.String(length=200), nullable=True),
    sa.Column('lora_weight', sa.Float(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('pict_revenue', sa.Integer(), nullable=True),
    sa.Column('dl_revenue', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', name='uq_sales_month')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('situation', sa.String(length=100), nullable=True),
    sa.Column('positive', sa.Text(), nullable=True),
    sa.Column('negative', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('story_chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('premise', sa.Text(), nullable=True),
    sa.Column('chapters_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('pixiv_url', sa.String(length=500), nullable=True),
    sa.Column('pict_url', sa.String(length=500), nullable=True),
    sa.Column('dl_url', sa.String(length=500), nullable=True),
    sa.Column('sales_pict', sa.Integer(), nullable=True),
    sa.Column('sales_dl', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('works')
    op.drop_table('stories')
    op.drop_table('prompts')
    op.drop_table('sales_records')
    op.drop_table('characters')
    # ### end Alembic commands ###
